# Imposta il tema grafico principale del sito
theme: jekyll-theme-Time-Slate
# Architect
# Cayman  *
# Dinky
# Leap-day
# Midnight
# Slate  *
# Time-machine  *

# Titolo principale gigante nel banner verde e nella scheda del browser
title: Luca Gaetano Sansalone

# Sottotitolo elegante che appare sotto al nome
description: Portfolio di Ingegneria Hardware/Software Codesign

# Mostra i pulsanti per scaricare i codici
show_downloads: true
